exec: /
	@echo 'test'
uniqueu: unique.c unsorted.c	
	gcc -o uniqueu unique.c unsorted.c
	time ./uniqueu ~/desktop/coen12/coencode/project2.c/text/Bible.txt
	time ./uniqueu ~/desktop/coen12/coencode/project2.c/text/Genesis.txt
	time ./uniqueu ~/desktop/coen12/coencode/project2.c/text/GreenEggsAndHam.txt
	time ./uniqueu ~/desktop/coen12/coencode/project2.c/text/HoundOfTheBaskervilles.txt
	time ./uniqueu ~/desktop/coen12/coencode/project2.c/text/Macbeth.txt
	time ./uniqueu ~/desktop/coen12/coencode/project2.c/text/TheCountOfMonteCristo.txt
	time ./uniqueu ~/desktop/coen12/coencode/project2.c/text/TheSecretGarden.txt
	time ./uniqueu ~/desktop/coen12/coencode/project2.c/text/TheWarOfTheWorlds.txt
	time ./uniqueu ~/desktop/coen12/coencode/project2.c/text/TreasureIsland.txt
	time ./uniqueu ~/desktop/coen12/coencode/project2.c/text/TwentyThousandLeagues.txt

parityu: parity.c unsorted.c
	gcc -o parityu parity.c unsorted.c
	time ./parityu ~/desktop/coen12/coencode/project2.c/text/testtext.txt
	time ./parityu ~/desktop/coen12/coencode/project2.c/text/Bible.txt
	time ./parityu ~/desktop/coen12/coencode/project2.c/text/Genesis.txt
	time ./parityu ~/desktop/coen12/coencode/project2.c/text/GreenEggsAndHam.txt
	time ./parityu ~/desktop/coen12/coencode/project2.c/text/HoundOfTheBaskervilles.txt
	time ./parityu ~/desktop/coen12/coencode/project2.c/text/Macbeth.txt
	time ./parityu ~/desktop/coen12/coencode/project2.c/text/TheCountOfMonteCristo.txt
	time ./parityu ~/desktop/coen12/coencode/project2.c/text/TheSecretGarden.txt
	time ./parityu ~/desktop/coen12/coencode/project2.c/text/TheWarOfTheWorlds.txt
	time ./parityu ~/desktop/coen12/coencode/project2.c/text/TreasureIsland.txt
	time ./parityu ~/desktop/coen12/coencode/project2.c/text/TwentyThousandLeagues.txt

bincountu: bincount.c unsorted.c
	gcc -o bincountu bincount.c unsorted.c
	time ./bincountu ~/desktop/coen12/coencode/project2.c/text/testtext.txt
	time ./bincountu ~/desktop/coen12/coencode/project2.c/text/Bible.txt
	time ./bincountu ~/desktop/coen12/coencode/project2.c/text/Genesis.txt
	time ./bincountu ~/desktop/coen12/coencode/project2.c/text/GreenEggsAndHam.txt
	time ./bincountu ~/desktop/coen12/coencode/project2.c/text/HoundOfTheBaskervilles.txt
	time ./bincountu ~/desktop/coen12/coencode/project2.c/text/Macbeth.txt
	time ./bincountu ~/desktop/coen12/coencode/project2.c/text/TheCountOfMonteCristo.txt
	time ./bincountu ~/desktop/coen12/coencode/project2.c/text/TheSecretGarden.txt
	time ./bincountu ~/desktop/coen12/coencode/project2.c/text/TheWarOfTheWorlds.txt
	time ./bincountu ~/desktop/coen12/coencode/project2.c/text/TreasureIsland.txt
	time ./bincountu ~/desktop/coen12/coencode/project2.c/text/TwentyThousandLeagues.txt

uniques: unique.c sorted.c
	gcc -o uniques unique.c sorted.c
	time ./uniques ~/desktop/coen12/coencode/project2.c/text/Bible.txt
	time ./uniques ~/desktop/coen12/coencode/project2.c/text/Genesis.txt
	time ./uniques ~/desktop/coen12/coencode/project2.c/text/GreenEggsAndHam.txt
	time ./uniques ~/desktop/coen12/coencode/project2.c/text/HoundOfTheBaskervilles.txt
	time ./uniques ~/desktop/coen12/coencode/project2.c/text/Macbeth.txt
	time ./uniques ~/desktop/coen12/coencode/project2.c/text/TheCountOfMonteCristo.txt
	time ./uniques ~/desktop/coen12/coencode/project2.c/text/TheSecretGarden.txt
	time ./uniques ~/desktop/coen12/coencode/project2.c/text/TheWarOfTheWorlds.txt
	time ./uniques ~/desktop/coen12/coencode/project2.c/text/TreasureIsland.txt
	time ./uniques ~/desktop/coen12/coencode/project2.c/text/TwentyThousandLeagues.txt

paritys: parity.c sorted.c
	gcc -o paritys parity.c sorted.c
	time ./paritys ~/desktop/coen12/coencode/project2.c/text/testtext.txt
	time ./paritys ~/desktop/coen12/coencode/project2.c/text/Bible.txt
	time ./paritys ~/desktop/coen12/coencode/project2.c/text/Genesis.txt
	time ./paritys ~/desktop/coen12/coencode/project2.c/text/GreenEggsAndHam.txt
	time ./paritys ~/desktop/coen12/coencode/project2.c/text/HoundOfTheBaskervilles.txt
	time ./paritys ~/desktop/coen12/coencode/project2.c/text/Macbeth.txt
	time ./paritys ~/desktop/coen12/coencode/project2.c/text/TheCountOfMonteCristo.txt
	time ./paritys ~/desktop/coen12/coencode/project2.c/text/TheSecretGarden.txt
	time ./paritys ~/desktop/coen12/coencode/project2.c/text/TheWarOfTheWorlds.txt
	time ./paritys ~/desktop/coen12/coencode/project2.c/text/TreasureIsland.txt
	time ./paritys ~/desktop/coen12/coencode/project2.c/text/TwentyThousandLeagues.txt

bincounts: bincount.c sorted.c
	gcc -o bincounts bincount.c sorted.c
	time ./bincounts ~/desktop/coen12/coencode/project2.c/text/testtext.txt
	time ./bincounts ~/desktop/coen12/coencode/project2.c/text/Bible.txt
	time ./bincounts ~/desktop/coen12/coencode/project2.c/text/Genesis.txt
	time ./bincounts ~/desktop/coen12/coencode/project2.c/text/GreenEggsAndHam.txt
	time ./bincounts ~/desktop/coen12/coencode/project2.c/text/HoundOfTheBaskervilles.txt
	time ./bincounts ~/desktop/coen12/coencode/project2.c/text/Macbeth.txt
	time ./bincounts ~/desktop/coen12/coencode/project2.c/text/TheCountOfMonteCristo.txt
	time ./bincounts ~/desktop/coen12/coencode/project2.c/text/TheSecretGarden.txt
	time ./bincounts ~/desktop/coen12/coencode/project2.c/text/TheWarOfTheWorlds.txt
	time ./bincounts ~/desktop/coen12/coencode/project2.c/text/TreasureIsland.txt
	time ./bincounts ~/desktop/coen12/coencode/project2.c/text/TwentyThousandLeagues.txt

	